// examples/react-example/host/src/main.jsx
import React from 'react';
import { createRoot } from 'react-dom/client';
import App from './App';

console.log(' Initializing React Native Federation Host...');

const container = document.getElementById('root');
const root = createRoot(container);

try {
 root.render(<App />);
 console.log(' React Host application started successfully');
} catch (error) {
 console.error(' Failed to start React Host application:', error);

 // Show error in DOM
 container.innerHTML = `
 <div style="color: red; padding: 20px; margin: 20px; border: 1px solid red; border-radius: 4px;">
 <h3> Failed to load React Host</h3>
 <p>Error: ${error.message}</p>
 <details>
 <summary>Error Details</summary>
 <pre>${error.stack}</pre>
 </details>
 </div>
 `;
}

// examples/angular-example/host/src/main.ts
import 'zone.js';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { CommonModule } from '@angular/common';
import { AppComponent } from './app/app.component';
import { FederationLoaderComponent } from './app/federation-loader.component';

@NgModule({
 declarations: [
 AppComponent
 ],
 imports: [
 BrowserModule,
 CommonModule,
 FederationLoaderComponent
 ],
 providers: [],
 bootstrap: [AppComponent]
})
class AppModule { }

async function bootstrap() {
 try {
 console.log(' Initializing Angular Native Federation Host...');

 await platformBrowserDynamic().bootstrapModule(AppModule);

 console.log(' Angular Host application started successfully');
 } catch (error) {
 console.error(' Failed to start Angular Host application:', error);
 }
}

bootstrap();
