// examples/angular-example/host/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
 selector: 'app-root',
 template: `
 <div class="app-container">
 <header class="app-header">
 <h1> Angular Host Application</h1>
 <p>Native Federation Angular Example</p>
 </header>

 <main class="app-main">
 <div class="section">
 <h2>Local Components</h2>
 <div class="local-content">
 <p>This content is served from the Angular Host application.</p>
 <button (click)="toggleMessage()" class="btn">{{ showMessage ? 'Hide' : 'Show' }} Local Message</button>
 <div *ngIf="showMessage" class="message">
 Hello from Angular Host!
 </div>
 </div>
 </div>

 <div class="section">
 <h2>Federated Components</h2>
 <app-federation-loader></app-federation-loader>
 </div>
 </main>
 </div>
 `,
 styles: [`
 .app-container {
 max-width: 1200px;
 margin: 0 auto;
 padding: 20px;
 }

 .app-header {
 background: linear-gradient(135deg, #1976d2, #42a5f5);
 color: white;
 padding: 30px;
 border-radius: 8px;
 text-align: center;
 margin-bottom: 30px;
 }

 .app-header h1 {
 margin: 0 0 10px 0;
 font-size: 2.5em;
 }

 .app-header p {
 margin: 0;
 opacity: 0.9;
 }

 .app-main {
 display: flex;
 flex-direction: column;
 gap: 30px;
 }

 .section {
 background: white;
 padding: 30px;
 border-radius: 8px;
 box-shadow: 0 2px 4px rgba(0,0,0,0.1);
 }

 .section h2 {
 margin: 0 0 20px 0;
 color: #1976d2;
 border-bottom: 2px solid #e3f2fd;
 padding-bottom: 10px;
 }

 .local-content {
 display: flex;
 flex-direction: column;
 gap: 15px;
 }

 .btn {
 background: #1976d2;
 color: white;
 border: none;
 padding: 12px 24px;
 border-radius: 4px;
 cursor: pointer;
 font-size: 16px;
 align-self: flex-start;
 transition: background-color 0.3s;
 }

 .btn:hover {
 background: #1565c0;
 }

 .message {
 background: #e8f5e8;
 color: #2e7d32;
 padding: 15px;
 border-radius: 4px;
 border-left: 4px solid #4caf50;
 }
 `]
})
export class AppComponent {
 showMessage = false;

 toggleMessage() {
 this.showMessage = !this.showMessage;
 }
}

// examples/react-example/host/src/App.jsx
import React, { useState } from 'react';
import FederationLoader from './FederationLoader';

const App = () => {
 const [showLocal, setShowLocal] = useState(false);

 const toggleMessage = () => {
 setShowLocal(!showLocal);
 };

 return (
 <div style={styles.appContainer}>
 <header style={styles.appHeader}>
 <h1> React Host Application</h1>
 <p>Native Federation React Example</p>
 </header>

 <main style={styles.appMain}>
 <div style={styles.section}>
 <h2>Local Components</h2>
 <div style={styles.localContent}>
 <p>This content is served from the React Host application.</p>
 <button onClick={toggleMessage} style={styles.btn}>
 {showLocal ? 'Hide' : 'Show'} Local Message
 </button>
 {showLocal && (
 <div style={styles.message}>
 Hello from React Host!
 </div>
 )}
 </div>
 </div>

 <div style={styles.section}>
 <h2>Federated Components</h2>
 <FederationLoader />
 </div>
 </main>
 </div>
 );
};

const styles = {
 appContainer: {
 maxWidth: '1200px',
 margin: '0 auto',
 padding: '20px'
 },

 appHeader: {
 background: 'linear-gradient(135deg, #61dafb, #21a0c4)',
 color: 'white',
 padding: '30px',
 borderRadius: '8px',
 textAlign: 'center',
 marginBottom: '30px'
 },

 appMain: {
 display: 'flex',
 flexDirection: 'column',
 gap: '30px'
 },

 section: {
 background: 'white',
 padding: '30px',
 borderRadius: '8px',
 boxShadow: '0 2px 4px rgba(0,0,0,0.1)'
 },

 localContent: {
 display: 'flex',
 flexDirection: 'column',
 gap: '15px'
 },

 btn: {
 background: '#61dafb',
 color: 'white',
 border: 'none',
 padding: '12px 24px',
 borderRadius: '4px',
 cursor: 'pointer',
 fontSize: '16px',
 alignSelf: 'flex-start',
 transition: 'background-color 0.3s'
 },

 message: {
 background: '#e8f5e8',
 color: '#2e7d32',
 padding: '15px',
 borderRadius: '4px',
 borderLeft: '4px solid #4caf50'
 }
};

export default App;
